backend:
  name: git-gateway
  branch: master

# Develop on a local repo
# Should be commented on master
local_backend: true

# Allow drafts
publish_mode: editorial_workflow

media_folder: "public/img/content/posts"
public_folder: "img/content/posts"

collections:
  - name: "tags"
    label: "Tags"
    folder: "content/tags"
    create: true
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Featured?", name: "featured", widget: "boolean", default: false, required: false}

  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Github", name: "github", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Medium", name: "medium", widget: "string", required: false}
      - {label: "GPG Key", name: "gpgKey", widget: "string", required: false}
      - {label: "Clubhouse", name: "clubhouse", widget: "string", required: false}
      - {label: "YouTube", name: "youtube", widget: "string", required: false}
      - {label: "Profile picture", name: "profilePicture", widget: "image", required: true}
      - {label: "Short bio", name: "shortBio", widget: "string", require: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{slug}}"
    sortable_fields: ["publishedOn", "title"]
    fields:
    - {label: "Published on", name: "publishedOn", widget: "date", required: false}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Sub title", name: "subTitle", widget: "string", required: false}
    - {label: "Canonical URL", name: "canonicalUrl", widget: "string", required: false}
    - {label: "Featured?", name: "featured", widget: "boolean", default: false, required: false}
    - {label: "Hero image", name: "heroImg", widget: "image", required: false}
    - {label: "Slug", name: "slug", widget: "string", required: false}
    - {label: "Tags", name: "tags", widget: "relation", collection: "tags", search_fields: ["title"], value_field: "slug", display_fields: ["title"], multiple: true, required: false}
    - {label: "Related posts", name: "relatedSlugs", widget: "relation", collection: "posts", search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"], multiple: true, required: false}
    - {label: "Author", name: "author", widget: "relation", collection: "authors", search_fields: ["name"], value_field: "slug", display_fields: ["name"]}
    - {label: "Body", name: "body", widget: "markdown"}
